project:
  type: website

website:
  title: "Oh wow - such beautiful website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        href: about.qmd

format:
  html:
    css: styles.css
