project:
  type: website

website:
  title: "Oh wow - such beautiful website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        href: about.qmd
      - text: Project EDV-Tek
        href: projekt-edv-tek.qmd
      - text: Research
        href: research.qmd

format:
  html:
    css: styles.css
