project:
  type: website

website:
  title: "/Users/juergenthiesen/Documents/GitHub/juergenct.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



